jwt.secretKey=asdlfadlheretuqyptuyptibfapiruytuaf72562562623952352afaksjdhsdvdnf

spring.cloud.gateway.server.webflux.routes[0].id=orderSystem
spring.cloud.gateway.server.webflux.routes[0].uri=lb://orderSystem
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=LoggingOrderFilter
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=Authentication
#can be accessed in conifg of loggingFilter
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.isEnabled=true

spring.cloud.gateway.server.webflux.routes[1].id=inventorySystem
spring.cloud.gateway.server.webflux.routes[1].uri=lb://inventorySystem
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventory/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=Authentication

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

server.port=8070

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.loadbalancer=TRACE
logging.level.org.springframework.cloud.netflix.eureka=DEBUG

management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=gateway

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
